elimu-ai/webapp

src/main/resources/db/migration/1001036.sql
Unknown table 'literacyapp.TaskEvent'
=> Fixed bug in db migration script

src/main/webapp/WEB-INF/jsp/admin/project/edit.jsp
=> #551 Bug: AppCategories disappear when the list of project managers is edited

src/main/java/ai/elimu/dao/jpa/ApplicationDaoJpa.java, src/main/java/ai/elimu/dao/jpa/ApplicationVersionDaoJpa.java, src/main/java/ai/elimu/rest/v1/application/ApplicationRestController.java, src/main/java/ai/elimu/rest/v1/project/AppCollectionRestController.java, src/main/webapp/WEB-INF/spring/applicationContext-jpa.xml, src/test/java/ai/elimu/dao/ApplicationDaoTest.java, src/test/java/ai/elimu/dao/ApplicationVersionDaoTest.java
=> #626 Implement usage of caching during database calls

src/main/java/ai/elimu/rest/v1/application/ApplicationRestController.java, src/main/java/ai/elimu/rest/v1/project/AppCollectionRestController.java, src/main/java/ai/elimu/service/JsonService.java, src/main/webapp/WEB-INF/spring/applicationContext-jpa.xml, src/main/webapp/WEB-INF/spring/applicationContext.xml
- Added applicationsInAppCollection cache
=> 626 Implement usage of caching during database calls

src/main/java/ai/elimu/web/project/app/AppCreateController.java, src/main/java/ai/elimu/web/project/app/AppEditController.java, src/main/webapp/WEB-INF/jsp/project/app/create.jsp, src/main/webapp/WEB-INF/jsp/project/app/edit.jsp
- List the ApplicationVersions of an Application
=> 634 Update existing Application

src/main/java/ai/elimu/web/project/app/AppCreateController.java, src/main/webapp/WEB-INF/jsp/project/app-category/list.jsp, src/main/webapp/WEB-INF/jsp/project/app-group/list.jsp
=> #634 Update existing Application

pom.xml, src/main/java/ai/elimu/rest/v1/JavaToGsonConverter.java
=> #651 Add versionName to ApplicationVersion

src/main/java/ai/elimu/web/project/license/LicenseCreateController.java
=> 661 Include AppCategory title(s) in the License e mail

pom.xml, src/main/java/ai/elimu/model/admin/Application.java, src/main/java/ai/elimu/rest/v1/JavaToGsonConverter.java, src/main/java/ai/elimu/web/project/app/AppCreateController.java, src/main/java/ai/elimu/web/project/app/AppEditController.java
=> #674 Make it possible to get an Application's AppCategory

pom.xml, src/main/java/ai/elimu/dao/jpa/ApplicationDaoJpa.java, src/main/java/ai/elimu/model/admin/ApplicationVersion.java, src/main/java/ai/elimu/rest/service/project/ProjectJsonService.java, src/main/java/ai/elimu/web/admin/application_version/ApplicationVersionCreateController.java, src/main/java/ai/elimu/web/project/app/AppCreateController.java, src/main/resources/db/migration/2000066.sql, src/main/webapp/WEB-INF/jsp/project/app/create.jsp, src/main/webapp/WEB-INF/jsp/publish.jsp
- Added ApplicationVersionStatus to ApplicationVersion
=> #682 Add pending APK approval functionality

src/main/webapp/WEB-INF/jsp/layout.jsp
This is my first pull request, so I hope everything is alright. The links are now fixed for the PROD environment, which has been manually tested and all links point toward correct links.
=> #690: Fixed language links pointing to the test domain

pom.xml
- Upgraded to commons-fileupload 1.4
=> #695 Fix potential security vulnerability in dependencies

src/main/java/ai/elimu/web/servlet/i18n/DomainLocaleResolver.java
- Add the New Locale to the DomainLocaleResolver
=> #696 Add support for Hindi language

src/main/resources/db/migration/2000085.sql
- "StoryBook" --> "StoryBook_paragraphs"
=> #714 Extract content from ePUB storybook

src/main/resources/db/migration/2000089.sql
- Delete Applications that belong to a custom Project's AppGroup.
=> #702 Delete support for custom Projects

src/main/java/ai/elimu/model/enums/Role.java, src/main/java/ai/elimu/web/SignOnController.java, src/main/resources/db/migration/2000093.sql, src/main/webapp/WEB-INF/jsp/admin/layout.jsp, src/main/webapp/WEB-INF/jsp/analytics/layout.jsp, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/spring/applicationContext-security.xml
- Delete role "PROJECT_MANAGER"
=> #702 Delete unused/unnecessary code

src/main/java/ai/elimu/web/content/word/WordListController.java
=> #741 Add educational content: Swahili

src/main/java/ai/elimu/web/content/allophone/AllophoneCsvExportController.java, src/main/webapp/WEB-INF/i18n/messages_en.properties, src/main/webapp/WEB-INF/jsp/admin/application/edit.jsp, src/main/webapp/WEB-INF/jsp/content/allophone/list.jsp
- Added CSV export of Allophones
=> #740 Export educational content to CSV files

src/main/java/ai/elimu/web/content/word/WordListController.java
- English: Added Allophones for "thirteen"
=> #777 Import content from CSV files on launch

src/main/java/ai/elimu/rest/v2/StoryBooksRestController.java, src/test/java/ai/elimu/rest/v2/StoryBooksRestControllerTest.java
=> #820 Add REST API for downloading StoryBooks

src/main/java/ai/elimu/model/content/Word.java, src/main/java/ai/elimu/web/content/word/WordCreateController.java, src/main/java/ai/elimu/web/content/word/WordEditController.java, src/main/webapp/WEB-INF/i18n/messages_en.properties, src/main/webapp/WEB-INF/jsp/content/word/create.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp
=> #829 Add root Word

src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterDeleteController.java
- Fixed bug with Image deletion
=> #845 Enable deletion of StoryBook chapters

src/main/java/ai/elimu/util/epub/EPubParagraphExtractionHelper.java, src/test/java/ai/elimu/util/epub/EPubParagraphExtractionHelperTest.java
- Remove from the beginning/end of paragraphs.
=> #859 Ignore `\n` during ePUB import

src/main/webapp/static/css/content/styles.css
- Right-align Urdu text in StoryBook editor preview
=> #863 Add support for Urdu

src/main/java/ai/elimu/util/db/DbContentImportHelper.java, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/resources/config.properties
- Add DB content to Bengali `TEST` server
=> #869 Add support for REST API regression tests for each language

src/main/java/ai/elimu/dao/ImageDao.java, src/main/java/ai/elimu/dao/jpa/ImageDaoJpa.java, src/main/java/ai/elimu/rest/v1/content/multimedia/ImageRestController.java, src/main/java/ai/elimu/rest/v2/content/ImagesRestController.java, src/main/java/ai/elimu/web/content/MainContentController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCreateController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageListController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookEditController.java, src/main/java/ai/elimu/web/content/word/WordCreateController.java, src/main/java/ai/elimu/web/content/word/WordEditController.java, src/test/java/ai/elimu/dao/ImageDaoTest.java, src/test/java/rest/v1/content/multimedia/audio/AudioRestControllerTest.java, src/test/java/rest/v1/content/multimedia/image/ImageRestControllerTest.java
=> #857 Remove usage of `Language` for content stored in the database

src/main/java/ai/elimu/dao/jpa/StoryBookLearningEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/WordLearningEventDaoJpa.java, src/main/java/ai/elimu/rest/v2/analytics/StoryBookLearningEventsRestController.java, src/main/java/ai/elimu/rest/v2/analytics/WordLearningEventsRestController.java, src/main/java/ai/elimu/util/AnalyticsHelper.java, src/test/java/ai/elimu/util/AnalyticsHelperTest.java
- Fixed bug with extracting Android ID from CSV filename
=> #896 Add REST API for receiving WordLearningEvents

src/main/java/ai/elimu/rest/v1/application/ApplicationRestController.java, src/main/java/ai/elimu/rest/v1/service/JsonService.java, src/main/java/ai/elimu/rest/v2/content/StoryBooksRestController.java, src/main/java/ai/elimu/rest/v2/service/StoryBooksJsonService.java, src/main/java/ai/elimu/web/admin/application/ApplicationEditController.java, src/main/java/ai/elimu/web/admin/application_version/ApplicationVersionCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookEditController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterDeleteController.java, src/main/webapp/WEB-INF/spring/applicationContext.xml
- Moved DAO calls from StoryBooksRestController to JsonService
=> #899 Add usage of caching for the StoryBooksRestController

src/main/webapp/WEB-INF/jsp/content/letter-to-allophone-mapping/edit.jsp
- Removed `letterToAllophoneMapping.revisionNumber`
=> #457 Extract most frequent sounds per letter

pom.xml, src/main/java/ai/elimu/model/content/Allophone.java, src/main/java/ai/elimu/model/content/Content.java, src/main/java/ai/elimu/model/content/Letter.java, src/main/java/ai/elimu/model/content/Syllable.java, src/main/java/ai/elimu/model/content/Word.java, src/main/java/ai/elimu/rest/v2/JpaToGsonConverter.java
- chore(refactor) Moved `usageCount` from Word to Content.
- Added `usageCount` to REST API
=> #867 Add usageCount to Words

src/main/java/ai/elimu/web/content/word/WordsPendingController.java, src/main/webapp/WEB-INF/i18n/messages_en.properties, src/main/webapp/WEB-INF/jsp/content/word/create.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp, src/main/webapp/WEB-INF/jsp/content/word/pending.jsp
- Add list of words extracted from storybooks that have not yet been added as `Word` entities.
=> #932 Improve UX/UI for content creators

src/main/webapp/WEB-INF/jsp/contributions/donate.jsp
=> #1000 Create page with instructions on how to donate funds to the DAO

.travis.yml, pom.xml
- Fix `NoClassDefFoundError: javax/activation/DataSource`
=> #1024 Upgrade to Java 11

src/main/resources/log4j2_TEST.xml
- Fetch language from the Jetty context file
=> #968 Add one Log4J configuration per language

src/main/java/ai/elimu/model/content/StoryBook.java, src/main/java/ai/elimu/model/enums/PeerReviewStatus.java, src/main/java/ai/elimu/web/content/peer_review/StoryBookPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookEditController.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/webapp/WEB-INF/i18n/messages_en.properties, src/main/webapp/WEB-INF/jsp/content/storybook/edit.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/list.jsp, src/main/webapp/static/css/content/styles.css
- Store a storybook's peer review status
=> #997 Add StoryBook peer review event

src/main/java/ai/elimu/rest/v2/crowdsource/contributor/ContributorRestController.java
- Prevent JSON response from failing in the case of a problem with sending the welcome e-mail.
- Do not use HTTP error code when a user already exists.
=> feat: #1120 Add REST API for creating Contributor

pom.xml
=> feat: #1128 Add support for Xhosa language

src/main/java/ai/elimu/model/enums/Role.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphEditController.java, src/main/webapp/WEB-INF/jsp/admin/layout.jsp, src/main/webapp/WEB-INF/jsp/analytics/layout.jsp, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/edit.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/paragraph/edit.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp
- This new role makes it possible for a contributor to delete storybook chapters and storybook paragraphs
=> feat: #1142 Add EDITOR role

src/main/java/ai/elimu/model/content/multimedia/Audio.java, src/main/java/ai/elimu/web/content/multimedia/audio/AudioCsvExportController.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2001161.sql, src/main/webapp/WEB-INF/jsp/content/multimedia/audio/create.jsp, src/main/webapp/WEB-INF/jsp/content/multimedia/audio/edit.jsp, src/main/webapp/WEB-INF/jsp/content/multimedia/audio/list.jsp
- Change `transcription` from text to textarea.
=> feat: #1160 Replace Audio transcription with title

src/main/java/ai/elimu/model/content/LetterToAllophoneMapping.java, src/main/java/ai/elimu/model/content/Word.java, src/main/java/ai/elimu/web/content/word/WordCsvExportController.java, src/main/webapp/WEB-INF/jsp/content/number/list.jsp, src/main/webapp/WEB-INF/jsp/contributions/most-recent.jsp
- Add `letter_to_allophone_mappings` to CSV export
=> refactor: #1178 Replace Allophones with LetterToAllophoneMappings

src/main/java/ai/elimu/rest/v2/crowdsource/AudioContributionsRestController.java, src/main/resources/config.properties
- Create new audio recordings: Word
=> feat: #952 Add REST API for crowdsourcing audio recordings

src/test/java/ai/elimu/rest/v2/crowdsource/AudioContributionsRestControllerTest.java, src/test/java/ai/elimu/rest/v2/crowdsource/AudioPeerReviewsRestControllerTest.java
=> feat: #952 Peer review existing audio recordings: Word

src/main/webapp/WEB-INF/jsp/content/multimedia/audio/list.jsp
This PR has been created to address the issue raised in #1263 , Only a change in the JSP file was required and no additional styling has been done.
=> Add word column to list of audios

src/main/webapp/WEB-INF/jsp/content/main.jsp, src/main/webapp/WEB-INF/jsp/contributions/most-recent.jsp
- Do not display contributor's e-mail in UI
=> feat: #1255 Add Web3 Authentication for Crypto-Newbies

src/main/webapp/WEB-INF/jsp/contributions/donate.jsp
=> #1320 Simplify the steps for donating cryptocurrency

src/main/java/ai/elimu/dao/WordPeerReviewEventDao.java, src/main/java/ai/elimu/dao/jpa/WordPeerReviewEventDaoJpa.java, src/main/java/ai/elimu/rest/v2/crowdsource/WordPeerReviewsRestController.java, src/main/java/ai/elimu/web/content/word/WordPeerReviewsController.java, src/main/webapp/WEB-INF/i18n/messages_en.properties, src/main/webapp/WEB-INF/jsp/content/main.jsp, src/main/webapp/WEB-INF/jsp/content/word/list.jsp, src/main/webapp/WEB-INF/jsp/content/word/peer-reviews/pending.jsp
Added a page to make it easier for contributors to know which words to peer-review next.
This list of word contributions events is sorted by time (oldest on top), and excludes any words contributed by the user currently signed in:
=> Feat #1324 add list of words pending peer review

src/main/webapp/WEB-INF/jsp/admin/layout.jsp, src/main/webapp/WEB-INF/jsp/analytics/layout.jsp, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp
=> feat: #1323 Integrate with the community token

src/main/java/ai/elimu/web/content/word/WordEditController.java, src/main/webapp/WEB-INF/i18n/messages_en.properties, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp
- Look up StoryBook Paragraphs that contain a Word
=> feat: #1375 Fetch list of storybooks where a word is used

pom.xml, src/main/resources/db/migration/2001232.sql
=> refactor: #1373 Rename to "Letter-sound correspondence"

src/main/webapp/WEB-INF/jsp/content/letter/edit.jsp
https://github.com/elimu-ai/webapp/issues/1393
=> Remove Audio Heading from Letter Edit page

src/main/webapp/WEB-INF/i18n/messages_en.properties, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/contributions/publish.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp
=> chore: #1463 Add Discord integration

src/main/java/ai/elimu/rest/v2/crowdsource/AudioContributionsRestController.java, src/main/java/ai/elimu/rest/v2/crowdsource/AudioPeerReviewsRestController.java, src/main/java/ai/elimu/rest/v2/crowdsource/WordContributionRestController.java, src/main/java/ai/elimu/rest/v2/crowdsource/WordPeerReviewsRestController.java, src/main/java/ai/elimu/util/DiscordHelper.java, src/main/java/ai/elimu/web/content/letter/LetterCreateController.java, src/main/java/ai/elimu/web/content/letter/LetterEditController.java, src/main/java/ai/elimu/web/content/letter_sound_correspondence/LetterSoundCorrespondenceCreateController.java, src/main/java/ai/elimu/web/content/letter_sound_correspondence/LetterSoundCorrespondenceEditController.java, src/main/java/ai/elimu/web/content/peer_review/AudioPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/StoryBookPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/WordPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookEditController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterCreateController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphCreateController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphEditController.java, src/main/java/ai/elimu/web/content/word/WordCreateController.java, src/main/java/ai/elimu/web/content/word/WordEditController.java
=> Feat #1463 add discord integration

src/main/java/ai/elimu/rest/v2/crowdsource/AudioContributionsRestController.java, src/main/java/ai/elimu/rest/v2/crowdsource/AudioPeerReviewsRestController.java, src/main/java/ai/elimu/rest/v2/crowdsource/WordContributionRestController.java, src/main/java/ai/elimu/rest/v2/crowdsource/WordPeerReviewsRestController.java, src/main/java/ai/elimu/util/DiscordHelper.java, src/main/java/ai/elimu/web/content/letter/LetterCreateController.java, src/main/java/ai/elimu/web/content/letter/LetterEditController.java, src/main/java/ai/elimu/web/content/letter_sound_correspondence/LetterSoundCorrespondenceCreateController.java, src/main/java/ai/elimu/web/content/letter_sound_correspondence/LetterSoundCorrespondenceEditController.java, src/main/java/ai/elimu/web/content/peer_review/AudioPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/StoryBookPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/WordPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookEditController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterCreateController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphCreateController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphEditController.java, src/main/java/ai/elimu/web/content/word/WordCreateController.java, src/main/java/ai/elimu/web/content/word/WordEditController.java
=> feat: #1463 Add Discord integration

src/main/java/ai/elimu/web/content/letter_sound_correspondence/LetterSoundCorrespondenceEditController.java, src/main/webapp/WEB-INF/jsp/content/letter-sound-correspondence/edit.jsp
=> feat: #1479 List the usages of a letter-sound correspondence

src/main/java/ai/elimu/web/content/sound/SoundEditController.java, src/main/webapp/WEB-INF/jsp/content/sound/edit.jsp
=> feat: #1518 List the letter-sound correspondences where a sound is used

src/main/webapp/WEB-INF/jsp/content/letter/list.jsp
Code to replace `True`/`False` with `Yes`/`No` in Diacritic column for a letter (`/content/letter/list`) in list.jsp
=> #1522 Replace True/False with Yes/No for Diacritic column for Letters

src/main/java/ai/elimu/util/epub/EPubImageExtractionHelper.java, src/main/java/ai/elimu/util/epub/EPubParagraphExtractionHelper.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/test/java/ai/elimu/util/epub/EPubImageExtractionHelperTest.java, src/test/java/ai/elimu/util/epub/EPubParagraphExtractionHelperTest.java, src/test/resources/ai/elimu/util/epub/eng-lra-377b7e63-6126-4cfe-bcee-1538d75c1b2f_Page_1.xhtml
=> fix: Incomplete import of ePUB from Let's Read #1527

src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/test/java/ai/elimu/util/epub/EPubChapterExtractionHelperTest.java, src/test/resources/ai/elimu/util/epub/hin-gdl-bear-walk.epub_nav.xhtml
=> fix: Import of Hindi ePUBs from Global Digital Library fails #1533

CONTRIBUTING.md, DB_MIGRATION.md, INSTALL.md, LOCALIZE.md, README.md, src/main/resources/config.properties, src/main/webapp/WEB-INF/jsp/content/emoji/create.jsp, src/main/webapp/WEB-INF/jsp/content/emoji/edit.jsp, src/main/webapp/WEB-INF/jsp/content/letter-sound-correspondence/create.jsp, src/main/webapp/WEB-INF/jsp/content/letter-sound-correspondence/edit.jsp, src/main/webapp/WEB-INF/jsp/content/letter/create.jsp, src/main/webapp/WEB-INF/jsp/content/letter/edit.jsp, src/main/webapp/WEB-INF/jsp/content/number/create.jsp, src/main/webapp/WEB-INF/jsp/content/number/edit.jsp, src/main/webapp/WEB-INF/jsp/content/sound/create.jsp, src/main/webapp/WEB-INF/jsp/content/sound/edit.jsp, src/main/webapp/WEB-INF/jsp/content/word/create.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp, src/main/webapp/WEB-INF/jsp/welcome.jsp
ref https://github.com/elimu-ai/wiki/issues/127
=> docs: Update references to old branch name

src/main/java/ai/elimu/rest/v2/analytics/LetterAssessmentEventsRestController.java, src/main/java/ai/elimu/rest/v2/analytics/LetterLearningEventsRestController.java, src/main/java/ai/elimu/rest/v2/analytics/StoryBookLearningEventsRestController.java, src/main/java/ai/elimu/rest/v2/analytics/WordAssessmentEventsRestController.java, src/main/java/ai/elimu/rest/v2/analytics/WordLearningEventsRestController.java, src/main/java/ai/elimu/util/AnalyticsHelper.java, src/test/java/ai/elimu/util/AnalyticsHelperTest.java
=> feat: Extract versionCode from CSV filename #1546

src/main/java/ai/elimu/rest/v2/crowdsource/ContributorsRestControllerGoogle.java, src/main/java/ai/elimu/rest/v2/crowdsource/ContributorsRestControllerWeb3.java, src/main/java/ai/elimu/util/Web3Helper.java, src/main/java/ai/elimu/web/SignOnControllerWeb3.java
=> Feat #1544 add rest api for signing in with web3

src/main/config/server-test/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-eng.xml, src/main/config/server-test/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-fil.xml, src/main/java/ai/elimu/web/SignOnControllerDiscord.java, src/main/java/ai/elimu/web/context/EnvironmentContextLoaderListener.java
Co-Authored-By: Shivaditya Shivganesh <53160903+sshivaditya2019@users.noreply.github.com>
=> feat: #1555 Configure Discord OAuth secret

src/main/webapp/static/js/web3provider.js
=> Fix #1576: Web3 providers rejection bug

.github/workflows/ci_main.yml, .github/workflows/ci_pr.yml, pom.xml
=> test: Add JaCoCo

.github/workflows/maven.yml, src/test/java/ai/elimu/dao/ApplicationDaoTest.java, src/test/java/ai/elimu/dao/ApplicationVersionDaoTest.java, src/test/java/ai/elimu/dao/BaseDaoTest.java, src/test/java/ai/elimu/dao/ContributorDaoTest.java, src/test/java/ai/elimu/dao/ImageDaoTest.java, src/test/java/ai/elimu/dao/NumberDaoTest.java, src/test/java/ai/elimu/dao/SoundDaoTest.java, src/test/java/ai/elimu/dao/WordContributionEventDaoTest.java
=> #1600 Include Windows OS in continuous integration

src/main/java/ai/elimu/web/SignOnControllerGitHub.java
=> 1126 Request e-mail during GitHub authentication

pom.xml
=> Upgrade to Java 11

.github/codecov.yml
https://docs.codecov.com/docs/commit-status#disabling-a-status
=> ci(codecov): disable "patch" status check

.github/codecov.yml
https://docs.codecov.com/docs/coverage-configuration#section-range
=> test(codecov): adjust color range

pom.xml, src/main/java/ai/elimu/rest/v2/JpaToGsonConverter.java
https://github.com/elimu-ai/model/releases/tag/model-2.0.68
closes https://github.com/elimu-ai/wiki/issues/134
=> build(model): bump to model-2.0.68

src/main/webapp/WEB-INF/jsp/admin/layout.jsp, src/main/webapp/WEB-INF/jsp/analytics/layout.jsp, src/main/webapp/WEB-INF/jsp/content/contributor/contributor-numbers.jsp, src/main/webapp/WEB-INF/jsp/content/contributor/contributor-storybooks.jsp, src/main/webapp/WEB-INF/jsp/content/contributor/contributor-summarized.jsp, src/main/webapp/WEB-INF/jsp/content/contributor/contributor-words.jsp, src/main/webapp/WEB-INF/jsp/content/contributor/list.jsp, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/content/letter-sound/edit.jsp, src/main/webapp/WEB-INF/jsp/content/letter-sound/peer-reviews/pending.jsp, src/main/webapp/WEB-INF/jsp/content/letter/edit.jsp, src/main/webapp/WEB-INF/jsp/content/main.jsp, src/main/webapp/WEB-INF/jsp/content/multimedia/audio/edit.jsp, src/main/webapp/WEB-INF/jsp/content/multimedia/image/edit.jsp, src/main/webapp/WEB-INF/jsp/content/number/edit.jsp, src/main/webapp/WEB-INF/jsp/content/number/peer-reviews/pending.jsp, src/main/webapp/WEB-INF/jsp/content/sound/edit.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/edit.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/peer-reviews/pending.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp, src/main/webapp/WEB-INF/jsp/content/word/peer-reviews/pending.jsp, src/main/webapp/WEB-INF/jsp/contributions/most-recent.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp
close https://github.com/elimu-ai/web3-wiki/issues/38
=> Identicons

.github/workflows/maven-build.yml, .github/workflows/maven-release.yml
=> ci(github): release workflow

src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/jdbc_PROD.properties, src/main/resources/jdbc_TEST.properties
=> #1696 correct db dialect

pom.xml
Required by Spring 6 (Jakarta EE)
refs #1698
=> chore(orm): upgrade to hibernate 5.6.x

src/main/java/ai/elimu/dao/LetterSoundPeerReviewEventDao.java, src/main/java/ai/elimu/dao/jpa/LetterSoundPeerReviewEventDaoJpa.java, src/main/java/ai/elimu/model/contributor/LetterSoundPeerReviewEvent.java, src/main/java/ai/elimu/web/content/letter_sound/LetterSoundPeerReviewsController.java, src/main/java/ai/elimu/web/content/peer_review/LetterSoundPeerReviewEventCreateController.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2004010.sql
refs #1677
> [!WARNING]
> Includes a DB migration script in `2004010.sql`.
=> refactor(dao): LetterSoundPeerReviewEvent

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.11
=> Release 2.4.11

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.12
=> Release 2.4.12

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.13
=> Release 2.4.13

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.14
=> Release 2.4.14

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.15
=> Release 2.4.15

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.16
=> Release 2.4.16

src/main/java/ai/elimu/web/content/contributor/ContributorCsvExportController.java, src/main/webapp/WEB-INF/jsp/content/contributor/list.jsp
Calculates the percentage impact per contributor.
close https://github.com/elimu-ai/web3-wiki/issues/41
=> feat(web3): export impact percentages to csv

src/main/resources/db/migration/2004020.sql
=> fix(sql): rename deviceId

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.21
=> Release 2.4.21

src/main/resources/db/migration/2004022.sql
=> chore(db): correct db migration script

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.22
=> Release 2.4.22

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.23
=> Release 2.4.23

src/main/java/ai/elimu/web/content/peer_review/LetterSoundPeerReviewEventCreateController.java
Issue # 1770 - Ensure consistent peer review status update
=> 1770 - Ensure consistent peer review status update

src/main/java/ai/elimu/util/csv/CsvAnalyticsExtractionHelper.java, src/main/java/ai/elimu/util/csv/CsvContentExtractionHelper.java, src/main/java/ai/elimu/util/db/DbContentImportHelper.java, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java
=> Reduce log output during app launch, to reduce waiting time during localhost development

pom.xml
=> fix(pom): javax.xml.XMLConstants scanned from multiple locations

pom.xml, src/main/java/ai/elimu/util/DiscordHelper.java
=> Dependabot/maven/org.owasp.antisamy antisamy 1.7.6

pom.xml
=> fix(pom): parameter optimize is deprecated

pom.xml, src/main/webapp/WEB-INF/spring/applicationContext.xml, src/main/webapp/WEB-INF/web.xml
=> refactor: remove max form content size

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.25
=> Release 2.4.25

pom.xml
=> Remove Javadoc plugin

src/main/config/DEPLOY.md
=> docs(deploy): fix wrong link to pom.xml

pom.xml
=> Remove verbose parameter from jetty-jspc-maven-plugin

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.26
=> Release 2.4.26

pom.xml, src/main/resources/jdbc_PROD.properties, src/main/resources/jdbc_TEST.properties
Closes #1826 
Update MySQL JDBC driver to use `com.mysql.cj.jdbc.Driver`
=> Update JDBC driver

README.md, pom.xml, src/main/config/DEPLOY.md, src/main/config/centos-stream-9/etc/default/jetty, src/main/config/centos-stream-9/etc/my.cnf, src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp-HIN.xml
=> build(jetty): upgrade to jetty 10.0.22

pom.xml
=> Release 2.4.31

src/main/config/DEPLOY.md
=> docs: update deploy instructions

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.32
Deploy to `PROD`:
* http://hin.elimu.ai
* http://tgl.elimu.ai
* http://eng.elimu.ai
=> Release 2.4.32

src/main/java/ai/elimu/web/context/EnvironmentContextLoaderListener.java, src/main/webapp/WEB-INF/jsp/layout.jsp, src/main/webapp/WEB-INF/jsp/welcome.jsp, src/main/webapp/static/css/content/styles.css, src/main/webapp/static/css/styles.css
Resolves #1842
Fetches the webapp version from `pom.xml`
<kbd>![image](https://github.com/user-attachments/assets/a2bb6755-924f-4569-a528-628fa80f54ea)</kbd>
=> Webapp version in footer

pom.xml
Include `pom.xml`
#1729
---
> [!NOTE]
=> format(spotless): include pom.xml

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.33
Release to `PROD`
---
> [!NOTE]
=> Release 2.4.33

pom.xml, src/main/webapp/WEB-INF/dispatcher-servlet.xml, src/main/webapp/WEB-INF/jsp/content/letter/list.jsp
=> Include JSPs and _all_ XMLs in format check 

src/main/webapp/WEB-INF/jsp/analytics/layout.jsp, src/main/webapp/WEB-INF/jsp/welcome.jsp, src/main/webapp/WEB-INF/spring/applicationContext-security.xml
=> feat: make analytics dashboard public

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.34
---
> [!NOTE]
=> Release 2.4.34

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.35
---
> [!NOTE]
=> Release 2.4.35

src/main/webapp/WEB-INF/jsp/analytics/letter-learning-event/list.jsp, src/main/webapp/WEB-INF/jsp/analytics/word-learning-event/list.jsp
=> refactor: time --> timestamp

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.36
---
> [!NOTE]
=> Release 2.4.36

src/main/java/ai/elimu/web/analytics/StoryBookLearningEventCsvExportController.java, src/main/webapp/WEB-INF/jsp/analytics/main.jsp, src/main/webapp/WEB-INF/jsp/analytics/storybook-learning-event/list.jsp, src/test/java/selenium/analytics/MainAnalyticsPage.java, src/test/java/selenium/analytics/StoryBookLearningEventsPage.java, src/test/java/selenium/analytics/StoryBookLearningEventsPageTest.java, src/test/java/selenium/analytics/WordLearningEventsPageTest.java
=> test(selenium): storybook learning events

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.38
---
> [!NOTE]
=> Release 2.4.38

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.39
---
> [!NOTE]
=> Release 2.4.39

src/main/webapp/WEB-INF/jsp/content/word/create.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp
Resolves #1841 
Applies suggested change to PR #1867 
For More details refer PR #1867 
---
> [!NOTE]
=> Applies suggested changes to PR #1867

.github/workflows/maven-regression-test-rest.yml, .github/workflows/maven-regression-test-ui.yml, pom.xml
=> test: rename maven profiles

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.41
---
> [!NOTE]
=> Release 2.4.41

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.42
---
> [!NOTE]
=> Release 2.4.42

pom.xml
https://jitpack.io/com/github/elimu-ai/webapp/webapp-2.4.44/build.log
=> Release 2.4.44

pom.xml
=> Revert "chore(deps): bump org.springframework:spring-webmvc from 5.3.18 to 6.1.13"

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.48
=> Release 2.4.48

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.49
=> Release 2.4.49

src/main/webapp/WEB-INF/jsp/admin/layout.jsp, src/main/webapp/WEB-INF/jsp/analytics/layout.jsp, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp, src/main/webapp/WEB-INF/jsp/sign-on-web3.jsp
=> fix: ui test blocked by wallet connect modal

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.50
=> Release 2.4.50

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.51
=> Release 2.4.51

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.52
=> Release 2.4.52

src/main/java/ai/elimu/model/analytics/LearningEvent.java, src/main/resources/META-INF/jpa-schema-export.sql
* Resolves #1910
---
* Make the data collection from Android apps more flexible/customizable.
* The `additionalData` field is optional, because learning events will not always contain this information.
* `mvn jetty:run`
* 
---
> [!NOTE]
=> Include additional data during data collection

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.53
=> Release 2.4.53

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.54
=> Release 2.4.54

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.55
=> Release 2.4.55

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.56
=> Release 2.4.56

src/test/java/selenium/analytics/MainAnalyticsPage.java, src/test/java/selenium/analytics/VideoLearningEventsPage.java, src/test/java/selenium/analytics/VideoLearningEventsPageTest.java
* Resolves #1894
* QA for the analytics dashboard
* 
* 
* 
---
> [!NOTE]
=> test(analytics): ui test for video learning events

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.58
=> Release 2.4.58

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.59
=> Release 2.4.59

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.60
=> Release 2.4.60

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.62
=> Release 2.4.62

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.63
=> Release 2.4.63

pom.xml
* Resolves #1969
* Facilitate future Hibernate upgrade
* 
* 
* 
---
> [!NOTE]
=> chore: upgrade mysql driver to v8.0.33

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.4.66
=> Release 2.4.66

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.5.0
=> Release 2.5.0

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.5.1
=> Release 2.5.1

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.5.2
=> Release 2.5.2

pom.xml
* #1982
* Test if upgrading to the latest version of Log4j fixes the bug.
* https://logging.apache.org/log4j/2.x/release-notes.html
* https://logging.apache.org/log4j/2.x/jakarta.html
* 
* 
---
> [!NOTE]
=> Integrate Log4j with Jakarta EE

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.5.3
=> Release 2.5.3

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.5.4
=> Release 2.5.4

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.5.6
Deployments:
* http://eng.elimu.ai
* http://hin.elimu.ai
* http://tgl.elimu.ai
* http://tha.elimu.ai
=> Release 2.5.6

pom-dependency-tree.txt, pom.xml
* Resolves #2001
* Quality assurance
* `mvn compile` will trigger the file generation
* `mvn compile`
* 
---
> [!NOTE]
=> chore: make dependency:tree part of the maven build phase

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.5.8
=> Release 2.5.8

src/main/java/ai/elimu/model/content/Emoji.java, src/main/java/ai/elimu/model/content/Letter.java, src/main/java/ai/elimu/model/content/LetterSound.java, src/main/java/ai/elimu/model/content/Number.java, src/main/java/ai/elimu/model/content/Sound.java, src/main/java/ai/elimu/model/content/StoryBook.java, src/main/java/ai/elimu/model/content/Word.java, src/main/java/ai/elimu/model/content/multimedia/Multimedia.java, src/main/java/ai/elimu/model/contributor/Contributor.java
* Resolves #2003 
* Make use of Jakarta Validations instead of old hibernate validations
* Imports and usage of @Size annotation instead of @Length
* Check imports and newly added annotation @Size
* Not Applicable
Not Applicable
---
> [!NOTE]
Reviewers: @jo-elimu @nya-elimu @gscdev
=> refactor: make use of jakarta validations (closes #2003)

pom.xml
https://github.com/elimu-ai/webapp/releases/tag/webapp-2.5.9
=> Release 2.5.9

.github/workflows/maven-regression-test-rest.yml, .github/workflows/maven-regression-test-ui.yml
* Resolves #
* The Hindi regression tests are unstable (out of memory errors), so switching to the new Thai deployment which contains less database content.
* 
* 
* 
---
> [!NOTE]
=> test: switch regression tests from hindi to thai

.github/workflows/maven-release.yml
* Resolves #2025
* Automatically perform a release whenever a pull request is merged into `main`.
* 
* 
* 
---
> [!NOTE]
=> build(release): release on push to main

src/main/java/ai/elimu/web/content/number/NumberListController.java
* Resolves #2045 
* To fix issue 2045
=> fix: add final to numberDao

pom-dependency-tree.txt, pom.xml
* Resolves #2050
* To remove unused dependencies in pom.xml
* To reduce the size of war file
* 
* 
---
> [!NOTE]
=> Removed unused dependencies from pom.xml #2050

pom-dependency-tree.txt, pom.xml, src/main/java/ai/elimu/rest/v2/JpaToGsonConverter.java
#285
Before:
```json
[{"bytesSize":4217,"revisionNumber":1,"videoFormat":"M4V","bytesUrl":"/video/1_r1.m4v","words":[],"id":1,"title":"test","usageCount":0}]
```
After:
```json
[{"bytesSize":4217,"revisionNumber":1,"videoFormat":"M4V","bytesUrl":"/video/1_r1.m4v","words":[],"id":1,"title":"test","usageCount":0,"thumbnailUrl":"/video/1_r1_thumbnail.png"}]
```
* Resolves #
* 
* 
* 
* 
---
> [!NOTE]
=> feat: add video thumbnail to rest api

pom-dependency-tree.txt, src/main/java/ai/elimu/model/content/Sound.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2005050.sql
* Resolves #1944
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: remove audio_id from sound table

src/main/resources/db/migration/2005050.sql
Remove `audio_id`
* Resolves #1944
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: drop foreign key for audio_id

pom-dependency-tree.txt, pom.xml
https://github.com/elimu-ai/webapp/pull/2036/commits/31eefae480361ce77ce52775b1722e4460df68b8
* Resolves #2021
* 
* 
* 
* 
---
> [!NOTE]
=> build: restore log4j output to console

pom-dependency-tree.txt, src/test/java/ai/elimu/rest/v2/content/NumbersRestControllerTest.java
* #2065
* 
* 
* 
* 
---
> [!NOTE]
=> test: regression tests for numbers

pom-dependency-tree.txt, src/main/webapp/static/css/content/styles.css
Make it easier for content creators by displaying letters using larger font.
* #1086
* 
* 
* 
* 
---
> [!NOTE]
=> feat: larger font-size during paragraph editing

pom-dependency-tree.txt, src/main/webapp/WEB-INF/jsp/content/letter-sound/create.jsp, src/main/webapp/WEB-INF/jsp/content/letter-sound/edit.jsp, src/main/webapp/WEB-INF/jsp/content/letter/create.jsp, src/main/webapp/WEB-INF/jsp/content/letter/edit.jsp, src/main/webapp/WEB-INF/jsp/content/number/create.jsp, src/main/webapp/WEB-INF/jsp/content/number/edit.jsp, src/main/webapp/WEB-INF/jsp/content/sound/create.jsp, src/main/webapp/WEB-INF/jsp/content/sound/edit.jsp, src/main/webapp/WEB-INF/jsp/content/word/create.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp
* Resolves #2016
* 
* 
* 
* 
---
> [!NOTE]
=> display links to external resources during thai content creation

src/main/java/ai/elimu/entity/contributor/Contributor.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2005064.sql
* Resolves #2084
* remove occupation field from contributor entity
=> closes #2084: remove occupation field from contributor entity

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/ContributorDao.java, src/main/java/ai/elimu/dao/jpa/ContributorDaoJpa.java, src/main/java/ai/elimu/entity/contributor/Contributor.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2005067.sql
* Resolves #2092
* Reduce code complexity.
* 
* 
* 
---
> [!NOTE]
=> 2092 remove provideridgoogle from contributor entity

pom.xml
https://github.com/spring-projects/spring-framework/releases/tag/v6.0.9
* Resolves #
* 
* 
* 
* 
---
> [!NOTE]
=> chore(build): spring-framework v6.0.9

pom-dependency-tree.txt, src/main/webapp/WEB-INF/jsp/admin/layout.jsp, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/content/letter-sound/edit.jsp, src/main/webapp/WEB-INF/jsp/content/letter-sound/peer-reviews/pending.jsp, src/main/webapp/WEB-INF/jsp/content/letter/edit.jsp, src/main/webapp/WEB-INF/jsp/content/multimedia/image/edit.jsp, src/main/webapp/WEB-INF/jsp/content/number/edit.jsp, src/main/webapp/WEB-INF/jsp/content/number/peer-reviews/pending.jsp, src/main/webapp/WEB-INF/jsp/content/sound/edit.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/edit.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/peer-reviews/pending.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp, src/main/webapp/WEB-INF/jsp/content/word/peer-reviews/pending.jsp, src/main/webapp/WEB-INF/jsp/contributor/contributor-numbers.jsp, src/main/webapp/WEB-INF/jsp/contributor/contributor-storybooks.jsp, src/main/webapp/WEB-INF/jsp/contributor/contributor-summarized.jsp, src/main/webapp/WEB-INF/jsp/contributor/contributor-words.jsp, src/main/webapp/WEB-INF/jsp/contributor/list.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp
* Resolves https://github.com/elimu-ai/web3-wiki/issues/76
* 
* 
* 
* 
---
> [!NOTE]
=> fix: png to svg

pom-dependency-tree.txt, src/main/java/ai/elimu/web/analytics/LetterLearningEventListController.java, src/main/java/ai/elimu/web/analytics/StoryBookLearningEventCsvExportController.java, src/main/java/ai/elimu/web/analytics/StoryBookLearningEventListController.java, src/main/java/ai/elimu/web/analytics/VideoLearningEventCsvExportController.java, src/main/java/ai/elimu/web/analytics/WordLearningEventListController.java
Redact Android IDs. Temporary measure until the Device ID gets implemented throughout the platform.
* Resolves #2103
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: redact android ids

src/main/java/ai/elimu/web/SignOnControllerWeb3.java, src/main/webapp/WEB-INF/jsp/sign-on-web3.jsp
* Resolves #2105
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: org mission

pom.xml
* Resolves #
* 
* 
* 
* 
---
> [!NOTE]
=> chore(deps): lombok 1.18.38

src/main/java/ai/elimu/web/analytics/WordLearningEventCsvExportController.java
* #856
* 
* 
* 
* 
---
> [!NOTE]
=> feat: add word learning event csv export

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/LetterSoundLearningEventDao.java, src/main/java/ai/elimu/dao/jpa/LetterSoundLearningEventDaoJpa.java, src/main/java/ai/elimu/entity/analytics/LetterSoundLearningEvent.java, src/main/java/ai/elimu/web/analytics/LetterSoundLearningEventCsvExportController.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/webapp/WEB-INF/spring/applicationContext-jpa.xml
* Resolves #1491
* 
* 
* 
* 
---
> [!NOTE]
=> feat: add letter-sound learning event

pom-dependency-tree.txt, src/main/java/ai/elimu/rest/v2/analytics/LetterSoundLearningEventsRestController.java, src/main/java/ai/elimu/rest/v2/analytics/StoryBookLearningEventsRestController.java, src/main/java/ai/elimu/rest/v2/analytics/VideoLearningEventsRestController.java, src/main/java/ai/elimu/rest/v2/analytics/WordLearningEventsRestController.java
* Resolves #1492
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: skip db storage during csv upload

pom-dependency-tree.txt, pom.xml, src/main/java/ai/elimu/entity/content/multimedia/Image.java, src/main/java/ai/elimu/rest/v2/JpaToGsonConverter.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCreateController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCsvExportController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2005084.sql
* #2060
* 
* 
* 
* 
---
> [!NOTE]
=> feat: calculate image checksum

pom-dependency-tree.txt, src/main/java/ai/elimu/entity/content/multimedia/Video.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2005088.sql
* #1934
* 
* 
* 
* 
---
> [!NOTE]
=> feat: add checksum for videos

pom-dependency-tree.txt, pom.xml, src/main/java/ai/elimu/entity/content/multimedia/Video.java, src/main/java/ai/elimu/rest/v2/JpaToGsonConverter.java, src/main/java/ai/elimu/web/content/multimedia/video/VideoCsvExportController.java, src/main/resources/META-INF/jpa-schema-export.sql
* Resolves #1934
* 
* 
* 
* 
---
> [!NOTE]
=> Move video storage to external location

pom-dependency-tree.txt, src/main/java/ai/elimu/entity/content/multimedia/Image.java
Quick fix for broken images for languages `ENG`, `HIN`, `TGL`, `THA`.
* #2126
* 
* 
* 
* 
---
> [!NOTE]
=> refactor(images): temporary fix until proper implementation

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/ImageDao.java, src/main/java/ai/elimu/dao/jpa/ImageDaoJpa.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCreateController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/webapp/WEB-INF/jsp/content/multimedia/image/edit.jsp, src/main/webapp/static/css/styles.css
* Resolves #2145
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: re-use images with same checksum

pom-dependency-tree.txt, src/main/java/ai/elimu/util/epub/EPubParagraphExtractionHelper.java, src/main/java/ai/elimu/util/linguistics/ThaiHelper.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/test/java/ai/elimu/util/epub/EPubParagraphExtractionHelperTest.java, src/test/java/ai/elimu/util/linguistics/ThaiHelperTest.java
* Resolves #1994
* 
* 
* 
* 
---
> [!NOTE]
=> add whitespaces thai

.github/workflows/maven-regression-tests-PROD.yml, .github/workflows/maven-regression-tests.yml, README.md, RELEASE.md, pom-dependency-tree.txt, pom.xml, src/main/config/DEPLOY.md, src/main/config/centos-stream-9/~/.elimu-ai/deploy-webapp.sh, src/main/java/ai/elimu/web/content/word/WordListController.java
* Resolves #2146
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: change jitpack groupId to `ai.elimu`

.github/workflows/maven-regression-tests-VIE.yml, INSTALL.md, LOCALIZE.md, README.md, TEST.md
* Resolves #2122
* Resolves #2158
* 
* 
* 
* 
---
> [!NOTE]
=> regresssion tests vietnamese

pom-dependency-tree.txt, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/webapp/WEB-INF/jsp/admin/application/edit.jsp, src/main/webapp/WEB-INF/jsp/admin/application/list.jsp, src/main/webapp/WEB-INF/jsp/admin/layout.jsp, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/content/letter-sound/edit.jsp, src/main/webapp/WEB-INF/jsp/content/letter/edit.jsp, src/main/webapp/WEB-INF/jsp/content/multimedia/image/edit.jsp, src/main/webapp/WEB-INF/jsp/content/number/edit.jsp, src/main/webapp/WEB-INF/jsp/content/sound/edit.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/edit.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp, src/main/webapp/WEB-INF/jsp/contributor/chip-contributor.jsp, src/main/webapp/WEB-INF/jsp/contributor/contributor-numbers.jsp, src/main/webapp/WEB-INF/jsp/contributor/contributor-storybooks.jsp, src/main/webapp/WEB-INF/jsp/contributor/contributor-words.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp, src/test/java/ai/elimu/rest/v2/applications/ApplicationsRestControllerTest.java, src/test/java/selenium/application/ApplicationCreatePage.java, src/test/java/selenium/application/ApplicationEditPage.java, src/test/java/selenium/application/ApplicationListPage.java, src/test/java/selenium/application/ApplicationTest.java
* #2158
* 
* 
* 
* 
---
> [!NOTE]
=> test: applications and application versions

pom-dependency-tree.txt, src/main/java/ai/elimu/entity/content/Letter.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2006010.sql, src/main/webapp/WEB-INF/jsp/content/letter/create.jsp, src/main/webapp/WEB-INF/jsp/content/letter/edit.jsp, src/main/webapp/WEB-INF/tags/formErrors.tag
* Resolves #1996
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: increase to max 4 characters in letter text

pom-dependency-tree.txt, pom.xml, src/main/webapp/WEB-INF/jsp/analytics/students/id.jsp, src/main/webapp/WEB-INF/jsp/analytics/students/list.jsp
* Resolves #2188
* 
* 
* 
* 
---
> [!NOTE]
=> fix: remove commons-io to avoid version conflict

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/LetterSoundLearningEventDao.java, src/main/java/ai/elimu/dao/StoryBookLearningEventDao.java, src/main/java/ai/elimu/dao/VideoLearningEventDao.java, src/main/java/ai/elimu/dao/WordLearningEventDao.java, src/main/java/ai/elimu/dao/jpa/LetterSoundLearningEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/StoryBookLearningEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/VideoLearningEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/WordLearningEventDaoJpa.java, src/main/java/ai/elimu/web/analytics/students/StudentController.java
* #2103
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: filter events by student

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/ImageDao.java, src/main/java/ai/elimu/dao/VideoDao.java, src/main/java/ai/elimu/dao/jpa/ImageDaoJpa.java, src/main/java/ai/elimu/dao/jpa/VideoDaoJpa.java, src/main/java/ai/elimu/util/GitHubLfsHelper.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCreateController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java, src/main/java/ai/elimu/web/content/multimedia/video/VideoCreateController.java, src/main/java/ai/elimu/web/content/multimedia/video/VideoEditController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/resources/config.properties
* Resolves #2230
* 
* 
* 
* 
---
> [!NOTE]
=> feat(lfs): handle existing files in lfs

pom-dependency-tree.txt, src/main/java/ai/elimu/web/content/peer_review/LetterSoundPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/NumberPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/StoryBookPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/WordPeerReviewEventCreateController.java, src/test/java/ai/elimu/util/epub/EPubImageExtractionHelperTest.java, src/test/java/ai/elimu/util/epub/EPubParagraphExtractionHelperTest.java, src/test/resources/ai/elimu/util/epub/tha-lra-c2d75faf-4145-424f-9f58-21182945d986.epub_Page_8.xhtml
* Resolves #2226
* 
* 
* 
* 
---
> [!NOTE]
=> test: nbsp in thai epub from lets read asia

src/main/java/ai/elimu/util/csv/CsvAnalyticsExtractionHelper.java
* Resolves #2234
* Needed by https://github.com/elimu-ai/analytics/issues/302
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: stop processing `android_id` column during data import

pom-dependency-tree.txt, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java
* Resolves #2126
* 
* 
* 
* 
---
> [!NOTE]
=> feat: handle image file updates

pom-dependency-tree.txt, src/main/java/ai/elimu/util/epub/EPubImageExtractionHelper.java, src/main/java/ai/elimu/util/epub/EPubParagraphExtractionHelper.java, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/webapp/WEB-INF/jsp/content/sound/list.jsp
* Resolves #2256
* 
* 
* 
* 
---
> [!NOTE]
=> feat: display sound distribution in pie chart

src/main/java/ai/elimu/rest/v2/content/EmojisRestController.java, src/main/java/ai/elimu/rest/v2/content/ImagesRestController.java, src/main/java/ai/elimu/rest/v2/content/LetterSoundsRestController.java, src/main/java/ai/elimu/rest/v2/content/LettersRestController.java, src/main/java/ai/elimu/rest/v2/content/NumbersRestController.java, src/main/java/ai/elimu/rest/v2/content/SoundsRestController.java, src/main/java/ai/elimu/rest/v2/content/VideosRestController.java, src/main/java/ai/elimu/rest/v2/content/WordsRestController.java, src/main/java/ai/elimu/rest/v2/service/StoryBooksJsonService.java
* Resolves #2259
* 
* 
* 
* 
---
> [!NOTE]
=> feat: exclude content that was rejected during peer-review

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/ImageDao.java, src/main/java/ai/elimu/dao/jpa/ImageDaoJpa.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java
* Resolves #2263
* 
* 
* 
* 
---
> [!NOTE]
=> fix: handle delayed processing in github api

pom-dependency-tree.txt, src/main/java/ai/elimu/util/DiscordHelper.java, src/main/java/ai/elimu/util/DomainHelper.java, src/main/java/ai/elimu/web/application/application_version/ApplicationVersionCreateController.java, src/main/java/ai/elimu/web/content/contributor/EditMotivationController.java, src/main/java/ai/elimu/web/content/letter/LetterCreateController.java, src/main/java/ai/elimu/web/content/letter/LetterEditController.java, src/main/java/ai/elimu/web/content/letter_sound/LetterSoundCreateController.java, src/main/java/ai/elimu/web/content/letter_sound/LetterSoundEditController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCreateController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java, src/main/java/ai/elimu/web/content/number/NumberCreateController.java, src/main/java/ai/elimu/web/content/number/NumberEditController.java, src/main/java/ai/elimu/web/content/peer_review/LetterSoundPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/sound/SoundCreateController.java, src/main/java/ai/elimu/web/content/sound/SoundEditController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookEditController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterCreateController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphCreateController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphEditController.java, src/main/java/ai/elimu/web/content/word/WordCreateController.java, src/main/java/ai/elimu/web/content/word/WordEditController.java
* Resolves #2265
* 
* 
* 
* 
---
> [!NOTE]
=> fix: slow response after editing vietnamese storybooks

pom-dependency-tree.txt, src/main/java/ai/elimu/util/csv/CsvAnalyticsExtractionHelper.java
* Letter-sound learning events
* Word assessment events
* Word learning events
* Storybook learning events
* Resolves #1910
* 
* 
* 
* 
---
> [!NOTE]
=> feat: handle additional data for all event types

pom-dependency-tree.txt, src/main/java/ai/elimu/entity/analytics/LetterSoundAssessmentEvent.java, src/main/java/ai/elimu/entity/analytics/LetterSoundLearningEvent.java, src/main/java/ai/elimu/entity/analytics/WordAssessmentEvent.java, src/main/java/ai/elimu/entity/analytics/WordLearningEvent.java, src/main/java/ai/elimu/tasks/analytics/LetterSoundAssessmentEventImportScheduler.java, src/main/java/ai/elimu/tasks/analytics/LetterSoundLearningEventImportScheduler.java, src/main/java/ai/elimu/tasks/analytics/NumberLearningEventImportScheduler.java, src/main/java/ai/elimu/tasks/analytics/StoryBookLearningEventImportScheduler.java, src/main/java/ai/elimu/tasks/analytics/VideoLearningEventImportScheduler.java, src/main/java/ai/elimu/tasks/analytics/WordAssessmentEventImportScheduler.java, src/main/java/ai/elimu/tasks/analytics/WordLearningEventImportScheduler.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2006072.sql
* Resolves #2275
* 
* 
* 
* 
---
> [!NOTE]
=> feat(data): lookup content by id

src/main/java/ai/elimu/util/csv/CsvAnalyticsExtractionHelper.java
* Resolves #2283
* 
* 
* 
* 
---
> [!NOTE]
=> fix: make learning event type optional

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/jpa/LetterSoundDaoJpa.java, src/main/webapp/WEB-INF/jsp/content/storybook/edit.jsp, src/test/java/selenium/content/storybook/StoryBookEditPage.java, src/test/java/selenium/content/word/WordTest.java
* Resolves #2287
* 
* 
* 
* 
---
> [!NOTE]
=> fix: illegal attempt to dereference collection

pom-dependency-tree.txt, pom.xml, src/main/config/centos-stream-9/etc/my.cnf, src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp-HIN.xml, src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp-TGL.xml, src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp-THA.xml, src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp-VIE.xml, src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp.xml, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/resources/META-INF/jpa-persistence.xml, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/jdbc_PROD.properties, src/main/webapp/WEB-INF/spring/applicationContext-jpa.xml
* Resolves #2290
* 
* 
* 
* 
---
> [!NOTE]
=> config(db): change dialect from mysql to mariadb

pom-dependency-tree.txt, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/jdbc_PROD.properties
* Resolves #2290
* 
* 
* 
* 
---
> [!NOTE]
=> config(db): change to mariadb dialect

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/ImageContributionEventDao.java, src/main/java/ai/elimu/dao/LetterContributionEventDao.java, src/main/java/ai/elimu/dao/LetterSoundContributionEventDao.java, src/main/java/ai/elimu/dao/NumberContributionEventDao.java, src/main/java/ai/elimu/dao/SoundContributionEventDao.java, src/main/java/ai/elimu/dao/StoryBookContributionEventDao.java, src/main/java/ai/elimu/dao/VideoContributionEventDao.java, src/main/java/ai/elimu/dao/WordContributionEventDao.java, src/main/java/ai/elimu/dao/jpa/ImageContributionEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/LetterContributionEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/LetterSoundContributionEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/NumberContributionEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/SoundContributionEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/StoryBookContributionEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/VideoContributionEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/WordContributionEventDaoJpa.java, src/main/java/ai/elimu/entity/contributor/VideoContributionEvent.java, src/main/java/ai/elimu/web/content/multimedia/video/VideoCreateController.java, src/main/java/ai/elimu/web/content/multimedia/video/VideoEditController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/java/ai/elimu/web/contributor/ContributorController.java, src/main/java/ai/elimu/web/contributor/ContributorCsvExportController.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/webapp/WEB-INF/jsp/contributor/contributor-summarized.jsp, src/main/webapp/WEB-INF/spring/applicationContext-jpa.xml, src/test/java/ai/elimu/dao/WordContributionEventDaoTest.java
* Resolves #1545
* 
* 
* 
* 
---
> [!NOTE]
=> feat: video contribution event

pom-dependency-tree.txt, src/main/java/ai/elimu/entity/analytics/StoryBookLearningEvent.java, src/main/resources/db/migration/2006107.sql
* Resolves #2310
* 
* 
* 
* 
---
> [!NOTE]
=> fix: make storybook id nullable

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/EmojiContributionEventDao.java, src/main/java/ai/elimu/dao/jpa/EmojiContributionEventDaoJpa.java, src/main/java/ai/elimu/entity/contributor/EmojiContributionEvent.java, src/main/java/ai/elimu/web/content/emoji/EmojiCreateController.java, src/main/java/ai/elimu/web/content/emoji/EmojiEditController.java, src/main/java/ai/elimu/web/contributor/ContributorCsvExportController.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/webapp/WEB-INF/jsp/content/emoji/edit.jsp, src/main/webapp/WEB-INF/spring/applicationContext-jpa.xml
* Resolves #759
* 
* 
* 
* 
---
> [!NOTE]
=> feat: emoji contribution events

src/main/java/ai/elimu/tasks/LetterSoundUsageCountScheduler.java, src/main/java/ai/elimu/tasks/LetterUsageCountScheduler.java, src/main/java/ai/elimu/tasks/ParagraphWordScheduler.java, src/main/java/ai/elimu/tasks/SoundUsageCountScheduler.java, src/main/java/ai/elimu/tasks/SyllableUsageCountScheduler.java, src/main/java/ai/elimu/tasks/WordUsageCountScheduler.java
* Resolves #2329
* 
* 
* 
* 
---
> [!NOTE]
=> feat(cron): improve error handling in scheduled tasks

pom-dependency-tree.txt, src/main/webapp/WEB-INF/jsp/content/storybook/chapter/edit.jsp
* Resolves #1102
* 
* 
* 
* 
---
> [!NOTE]
=> feat: delete storybook chapter

src/main/java/ai/elimu/tasks/WordUsageCountScheduler.java
* Resolves #2328
* 
* 
* 
* 
---
> [!NOTE]
=> fix: nullpointer in word usage count scheduler
