pom.xml
Upgraded org.slf4j to latest "safest" version as 1.8.x is still in alpha on maven repository so we don't need to rush it, IMHO
=> Upgrading org.slf4j

.gitignore, pom.xml, src/main/java/ai/elimu/util/MailChimpApiHelper.java, src/test/java/selenium/DomainHelper.java, src/test/java/selenium/web/WelcomePage.java, src/test/java/selenium/web/WelcomePageTest.java, src/test/java/selenium/web/admin/project/ProjectListPage.java, src/test/java/selenium/web/admin/project/ProjectListTest.java
In order to be able to run selenium tests on newer versions of firefox without problems, I have upgraded the selenium dependency to 3.0.1.
In order to use it, we need gecko driver (new web driver for Firefox). 
I used **gecko driver 0.14**, anything higher causes bugs. 
**Should the build fail** because of tests, we need to add this gecko driver to our server. 
In order to do that: 
Download driver from github: 
`wget https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz` 
Extract: `tar -xvzf geckodriver*` 
Make it executable: `chmod +x geckodriver`
Add it to our bin: `sudo mv geckodriver /usr/local/bin/`
=> #523 Create regression test for /admin/project/list [2-4h]

src/main/config/server-test/usr/local/jetty-distribution-9.3.8.v20160314/webapps/literacyapp.xml
603 - In the literacyapp.xml for Jetty 9 appstore_secret attribute is missing (getting NullPointerException)
=> #603: literacyapp.xml for Jetty 9 appstore_secret attribute is missing

src/main/resources/db/migration/2000054.sql
- Do not require AppCategory ids to be unique across multiple
AppCollections
=> 639 Fix DataIntegrityViolationException

src/main/resources/db/migration/2000085.sql
- Fix for "com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'paragraphs' at row 1"
- Increase length of "paragraphs" column from 255 to 1000.
=> #714 Extract content from ePUB storybook

src/main/java/ai/elimu/web/content/MainContentController.java
This PR adds a condition in `MainContentController` to redirect to `/content/contributor/edit-motivation` only if the environment isn't `dev`.
This way localhost environments do not redirect to the Edit Motivation page on logging in.
Do let me know if you would rather prefer for the condition to be extracted into a separate function `isContributorADeveloper()` in a new Utils class/`EnvironmentContextLoaderListener` for better readability.
=> [#1401] Skip Edit Contribution Page for localhost development

src/main/java/ai/elimu/web/content/contributor/EditMotivationController.java, src/main/java/ai/elimu/web/content/letter/LetterCreateController.java, src/main/java/ai/elimu/web/content/letter/LetterEditController.java, src/main/java/ai/elimu/web/content/letter_sound_correspondence/LetterSoundCorrespondenceCreateController.java, src/main/java/ai/elimu/web/content/letter_sound_correspondence/LetterSoundCorrespondenceEditController.java, src/main/java/ai/elimu/web/content/multimedia/audio/AudioCreateController.java, src/main/java/ai/elimu/web/content/multimedia/audio/AudioEditController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCreateController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java, src/main/java/ai/elimu/web/content/number/NumberCreateController.java, src/main/java/ai/elimu/web/content/number/NumberEditController.java, src/main/java/ai/elimu/web/content/peer_review/AudioPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/LetterSoundCorrespondencePeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/NumberPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/StoryBookPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/peer_review/WordPeerReviewEventCreateController.java, src/main/java/ai/elimu/web/content/sound/SoundCreateController.java, src/main/java/ai/elimu/web/content/sound/SoundEditController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookEditController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterCreateController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphCreateController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphEditController.java, src/main/java/ai/elimu/web/content/word/WordCreateController.java, src/main/java/ai/elimu/web/content/word/WordEditController.java, src/test/java/ai/elimu/dao/WordContributionEventDaoTest.java, src/test/java/ai/elimu/web/content/word/WordCreateControllerTest.java
=> #1606 context loader listener not initialized during controller tests

src/main/java/ai/elimu/web/SignOnControllerDiscord.java
**Description**
Changes Made:
Enhanced handling of the avatar field in SignOnControllerDiscord.java to ensure robust behavior when the avatar is missing or not a string.
**Details:**
I added validation to check for the avatar field in the JSON response, implemented logic to handle empty or non-string avatar fields, and introduced a default avatar URL fallback mechanism.
**Impact:**
This update ensures the application handles sign-on scenarios without Discord avatars gracefully and consistently, providing a stable user experience.
**Testing:**
Tested locally to verify functionality across different scenarios (avatar present, empty avatar).
**Note:**
The default avatar URL (https://e7.pngegg.com/pngimages/84/165/png-clipart-united-states-avatar-organization-information-user-avatar-service-co …
=> Error while signing on using Discord if no avatar #1649

DEPLOY.md, INSTALL.md, README.md, pom.xml, src/main/config/DEPLOY.md, src/main/config/centos-stream-9/etc/default/jetty, src/main/config/centos-stream-9/opt/jetty-base/start.d/http.ini, src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp.xml
=> build(jetty): upgrade to 10.0.21

src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp.xml, src/main/config/server-prod/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-eng.xml, src/main/config/server-prod/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-fil.xml, src/main/config/server-test/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-eng.xml, src/main/config/server-test/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-fil.xml, src/main/java/ai/elimu/web/context/EnvironmentContextLoaderListener.java
=> refactor(tts): remove google api secret

src/main/java/ai/elimu/model/contributor/ContributionEvent.java, src/main/java/ai/elimu/util/db/DbContentImportHelper.java, src/main/java/ai/elimu/web/content/letter/LetterCreateController.java, src/main/java/ai/elimu/web/content/letter/LetterEditController.java, src/main/java/ai/elimu/web/content/letter_sound/LetterSoundCreateController.java, src/main/java/ai/elimu/web/content/letter_sound/LetterSoundEditController.java, src/main/java/ai/elimu/web/content/multimedia/audio/AudioCreateController.java, src/main/java/ai/elimu/web/content/multimedia/audio/AudioEditController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCreateController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java, src/main/java/ai/elimu/web/content/number/NumberCreateController.java, src/main/java/ai/elimu/web/content/number/NumberEditController.java, src/main/java/ai/elimu/web/content/sound/SoundCreateController.java, src/main/java/ai/elimu/web/content/sound/SoundEditController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookEditController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterCreateController.java, src/main/java/ai/elimu/web/content/storybook/chapter/StoryBookChapterDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphCreateController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphDeleteController.java, src/main/java/ai/elimu/web/content/storybook/paragraph/StoryBookParagraphEditController.java, src/main/java/ai/elimu/web/content/word/WordCreateController.java, src/main/java/ai/elimu/web/content/word/WordEditController.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2004004.sql
ref #1674
> [!NOTE]
> Includes DB migration SQL script for altering existing databases in production: https://github.com/elimu-ai/webapp/commit/6cd2dfec3c539a3c53d20af995fa37959aee5753#diff-ecca7b129fd84cb80790d5006843f71ec549a30959eb2796fd11f91bd7f309b5
=> refactor(crowdsource): remove platform from contribution events

src/main/java/ai/elimu/dao/jpa/LetterSoundContributionEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/LetterSoundPeerReviewEventDaoJpa.java, src/main/java/ai/elimu/model/contributor/LetterSoundCorrespondenceContributionEvent.java, src/main/java/ai/elimu/util/db/DbContentImportHelper.java, src/main/java/ai/elimu/web/content/letter_sound/LetterSoundCreateController.java, src/main/java/ai/elimu/web/content/letter_sound/LetterSoundEditController.java, src/main/java/ai/elimu/web/content/peer_review/LetterSoundPeerReviewEventCreateController.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2004008.sql, src/main/webapp/WEB-INF/jsp/content/letter-sound/peer-reviews/pending.jsp
refs #1677
> [!WARNING]
> Includes DB migration script for renaming a column in production from `letterSoundCorrespondence_id` to `letterSound_id`.
Current structure in the production database:
```sql
MariaDB [webapp-HIN]> SHOW CREATE TABLE LetterSoundCorrespondenceContributionEvent;
```
```sql
| LetterSoundCorrespondenceContributionEvent | CREATE TABLE `LetterSoundCorrespondenceContributionEvent` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`comment` varchar(1000) DEFAULT NULL,
`revisionNumber` int(11) NOT NULL,
`time` datetime NOT NULL,
`timeSpentMs` bigint(20) NOT NULL,
`contributor_id` bigint(20) NOT NULL,
`letterSoundCorrespondence_id` bigint(20) NOT NULL,
PRIMARY KEY (`id`),
KEY `FKouellxtx1de1wpddv5x72h9jn` (`contributor_id`),
KEY `FKm1rttrlv6gxibd85a5sc3c4js` …
```
=> refactor(dao): LetterSoundCorrespondenceContributionEvent#letterSounds

src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java
=> refactor(servlet): remove hardcoded package name

src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp-TGL.xml, src/main/config/centos-stream-9/opt/jetty-base/webapps/webapp.xml, src/main/config/server-prod/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-eng.xml, src/main/config/server-prod/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-fil.xml, src/main/config/server-test/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-eng.xml, src/main/config/server-test/usr/local/jetty-distribution-9.4.31.v20200723/webapps/webapp-fil.xml, src/main/java/ai/elimu/web/context/EnvironmentContextLoaderListener.java, src/main/resources/config.properties, src/main/webapp/WEB-INF/jsp/contributions/donate.jsp
refs https://github.com/elimu-ai/web3-wiki/issues/10
=> Remove Covalent integration

src/main/java/ai/elimu/web/content/word/WordCsvExportController.java
refs #1743 
Optimizing JSON processing inside the loop using Java Streams.
=> #1743 - Refactor code to use Java Streams for JSON processing

pom.xml
This PR addresses issue #1742  by updating the dependency coordinates for Hibernate Validator in the pom.xml file. The artifact org.hibernate:hibernate-validator:jar:6.1.7.Final has been relocated to org.hibernate.validator:hibernate-validator:6.1.7.Final. This change resolves the warning related to the relocated artifact and ensures the correct version is used.
- Updated the pom.xml file to use the correct dependency coordinates for Hibernate Validator.
- Ran mvn clean compile to ensure the project compiles successfully without warnings.
- Verified that all existing tests pass.
- This PR is based on the update-dependencies branch.
- No additional changes were made beyond updating the dependency coordinates.
=> Update Hibernate Validator dependency coordinates

src/main/config/centos-stream-9/~/.elimu-ai/deploy-webapp.sh
Usage: `./deploy-webapp 2.4.23`
refs #1792
=> Add deployment script

.github/workflows/maven-regression-test.yml
Verifies that the REST API is returning data.
Not optimal, because it doesn't test the changes introduced in PRs triggering the test. It only tests the current deployment in production. But at least this helps us get faster notifications when the REST API breaks in production.
> [!NOTE]
> The future goal is to launch the webapp on localhost (as part of a GitHub Action workflow), and run these regression tests against http://localhost:8080/webapp/rest/ for every pull request. This change is a step in that direction.
closes #1768
=> test(rest): add regression testing to github action

.github/workflows/maven-build.yml, .github/workflows/maven-regression-test.yml, .github/workflows/maven-release.yml, pom.xml, src/main/config/DEPLOY.md
=> Upgrade to Java 17

pom.xml, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/resources/ai/elimu/web/content/storybook/step2_2_model.pmml
Resolves #1821
Relates to https://github.com/elimu-ai/ml-storybook-reading-level/pull/15
=> feat(ml): predict reading level during epub import

src/main/java/ai/elimu/web/analytics/StoryBookLearningEventListController.java, src/main/java/ai/elimu/web/analytics/WordLearningEventListController.java, src/main/webapp/WEB-INF/jsp/analytics/main.jsp, src/main/webapp/WEB-INF/jsp/analytics/storybook-learning-event/list.jsp, src/main/webapp/WEB-INF/jsp/analytics/word-learning-event/list.jsp, src/test/java/ai/elimu/rest/v2/content/EmojisRestControllerTest.java, src/test/java/ai/elimu/rest/v2/content/ImagesRestControllerTest.java, src/test/java/ai/elimu/rest/v2/content/LetterSoundsRestControllerTest.java, src/test/java/ai/elimu/rest/v2/content/LettersRestControllerTest.java, src/test/java/ai/elimu/rest/v2/content/SoundsRestControllerTest.java, src/test/java/ai/elimu/rest/v2/content/StoryBooksRestControllerTest.java, src/test/java/ai/elimu/rest/v2/content/WordsRestControllerTest.java, src/test/java/selenium/WelcomePage.java, src/test/java/selenium/WelcomePageTest.java, src/test/java/selenium/analytics/MainAnalyticsPage.java, src/test/java/selenium/analytics/MainAnalyticsPageTest.java, src/test/java/selenium/analytics/WordLearningEventsPage.java, src/test/java/selenium/analytics/WordLearningEventsPageTest.java, src/test/java/selenium/util/DomainHelper.java, src/test/java/selenium/util/ErrorHelper.java, src/test/java/selenium/util/ErrorPage.java, src/test/java/selenium/util/JavaScriptHelper.java, src/test/java/selenium/util/MarkupValidationHelper.java, src/test/java/selenium/util/SignOnHelper.java
Add UI tests.
#411
---
> [!NOTE]
=> test(selenium): word learning events

src/main/java/ai/elimu/web/analytics/StoryBookLearningEventCsvExportController.java
=> fix(csv): handle nullpointer when no `storybook_id` in database

src/main/java/ai/elimu/model/analytics/LearningEvent.java, src/main/java/ai/elimu/web/analytics/StoryBookLearningEventCsvExportController.java, src/main/resources/db/analytics_TEST/eng/storybook-learning-events.csv
=> refactor(analytics): obfuscate android id

src/main/webapp/WEB-INF/jsp/admin/layout.jsp, src/main/webapp/WEB-INF/jsp/analytics/layout.jsp, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp, src/main/webapp/static/css/content/styles.css, src/main/webapp/static/css/styles.css
=> refactor: remove custom fonts

src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp, src/main/webapp/static/css/styles.css
Resolves #1417
This PR provides fixes to the UI of the topbar mainly, moving the "connect wallet" to the side nav in smaller devices, adding ellipsis if the name of the contributor is long.
Just minor html and css changes.
Please check on different screen sizes if this resolves the issue #1417
Moved 'Connect wallet' to side nav in small screens:
displaying ellipsis when contributor name is long:
Name further compacted in screens below 1000px in width:
---
> [!NOTE]
=> 1417 improve the navigation bar UI

src/main/webapp/WEB-INF/jsp/contributor/contributor.jsp, src/main/webapp/WEB-INF/jsp/contributor/list.jsp, src/test/java/selenium/contributor/ContributorListPage.java, src/test/java/selenium/contributor/ContributorPage.java, src/test/java/selenium/contributor/ContributorPageTest.java
=> test: contributor page

src/main/java/ai/elimu/model/analytics/LearningEvent.java, src/main/java/ai/elimu/model/analytics/VideoLearningEvent.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/webapp/WEB-INF/jsp/admin/layout.jsp, src/main/webapp/WEB-INF/jsp/analytics/layout.jsp, src/main/webapp/WEB-INF/jsp/content/layout.jsp, src/main/webapp/WEB-INF/jsp/layout.jsp, src/main/webapp/WEB-INF/jsp/welcome.jsp, src/main/webapp/static/css/content/styles.css, src/main/webapp/static/css/styles.css
* #1894
* Collect data on learning events for videos
* 
* 
* 
---
> [!NOTE]
=> feat(entity): video learning event

src/main/java/ai/elimu/util/AnalyticsHelper.java, src/main/java/ai/elimu/util/csv/CsvAnalyticsExtractionHelper.java, src/main/java/ai/elimu/web/analytics/MainAnalyticsController.java, src/main/java/ai/elimu/web/analytics/VideoLearningEventCsvExportController.java, src/main/java/ai/elimu/web/analytics/VideoLearningEventListController.java, src/main/webapp/WEB-INF/jsp/analytics/layout.jsp, src/main/webapp/WEB-INF/jsp/analytics/main.jsp, src/main/webapp/WEB-INF/jsp/analytics/video-learning-event/list.jsp, src/main/webapp/static/css/styles.css, src/test/java/ai/elimu/util/AnalyticsHelperTest.java
* Resolves #1894
* To make video learning events available for download and visualization.
* Fetches video learning events from the database, and lists them in a UI.
* http://localhost:8080/webapp/analytics
* 
---
> [!NOTE]
=> feat(analytics): add video learning events to dashboard

src/main/java/ai/elimu/dao/VideoLearningEventDao.java, src/main/java/ai/elimu/dao/enums/OrderDirection.java, src/main/java/ai/elimu/dao/jpa/VideoLearningEventDaoJpa.java, src/main/java/ai/elimu/web/analytics/VideoLearningEventCsvExportController.java, src/main/java/ai/elimu/web/analytics/VideoLearningEventListController.java, src/main/resources/db/analytics_PROD/eng/video-learning-events.csv
* Resolves #1894
* Order descending for analytics dashboard, and ascending for CSV export.
* 
* 
* 
---
> [!NOTE]
=> fix(analytics): order by timestamp

src/main/java/ai/elimu/web/content/multimedia/image/ImageCsvExportController.java, src/main/webapp/WEB-INF/jsp/content/multimedia/image/edit.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/create.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/edit.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/list.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/peer-reviews/pending.jsp, src/main/webapp/static/css/styles.css
* Resolves #1933
* 
* 
* 
* 
---
> [!NOTE]
=> Add CID to CSV export

src/main/java/ai/elimu/web/analytics/VideoLearningEventListController.java, src/main/webapp/WEB-INF/jsp/analytics/video-learning-event/list.jsp
* Resolves #1894
* Needed because the page doesn't load when the database query returns hundreds of thousands of events.
* 
* 
* 
---
> [!NOTE]
=> refactor(analytics): limit to 100 most recent video learning events

src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/jdbc_PROD.properties, src/main/resources/jdbc_TEST.properties
* Resolves #1966
* Needed when upgrading to Hibernate 6.
* 
* Deploy release and test changes.
* 
---
> [!NOTE]
=> refactor: upgrade hibernate dialect

src/main/java/ai/elimu/dao/EmojiDao.java, src/main/java/ai/elimu/dao/ImageDao.java, src/main/java/ai/elimu/dao/LetterDao.java, src/main/java/ai/elimu/dao/LetterSoundDao.java, src/main/java/ai/elimu/dao/NumberDao.java, src/main/java/ai/elimu/dao/SoundDao.java, src/main/java/ai/elimu/dao/StoryBookDao.java, src/main/java/ai/elimu/dao/VideoDao.java, src/main/java/ai/elimu/dao/WordDao.java, src/main/java/ai/elimu/dao/jpa/EmojiDaoJpa.java, src/main/java/ai/elimu/dao/jpa/ImageDaoJpa.java, src/main/java/ai/elimu/dao/jpa/LetterDaoJpa.java, src/main/java/ai/elimu/dao/jpa/LetterSoundDaoJpa.java, src/main/java/ai/elimu/dao/jpa/NumberDaoJpa.java, src/main/java/ai/elimu/dao/jpa/SoundDaoJpa.java, src/main/java/ai/elimu/dao/jpa/StoryBookDaoJpa.java, src/main/java/ai/elimu/dao/jpa/VideoDaoJpa.java, src/main/java/ai/elimu/dao/jpa/WordDaoJpa.java, src/main/java/ai/elimu/web/content/emoji/EmojiCsvExportController.java, src/main/java/ai/elimu/web/content/letter/LetterCsvExportController.java, src/main/java/ai/elimu/web/content/letter_sound/LetterSoundCsvExportController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCsvExportController.java, src/main/java/ai/elimu/web/content/multimedia/video/VideoCsvExportController.java, src/main/java/ai/elimu/web/content/number/NumberCsvExportController.java, src/main/java/ai/elimu/web/content/sound/SoundCsvExportController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCsvExportController.java, src/main/java/ai/elimu/web/content/word/WordCsvExportController.java
* Resolves #1997 
* To sort the exports by ID instead of Usage
* Replaces usage of real all by usage with new read all by ID
* By invoking `/content/letter/list/letters.csv`  and `/content/sound/list/sounds.csv`
* Not Applicable
Not Applicable
---
> [!NOTE]
Reviewers: @jo-elimu @nya-elimu @gscdev
=> #1997 sort by id during csv export

pom-dependency-tree.txt, pom.xml
…ses #2004)
* Resolves #2004 
* Remove outdated JUnit 3.8.2 dependency that comes transitively through jlayer
* exclusion from pom.xml
* Check `pom-dependency-tree.txt`
* Not Applicable
Not Applicable
---
> [!NOTE]
Reviewers: @jo-elimu @nya-elimu @gscdev
=> refactor: exclude outdated JUnit 3.8.2 dependency through jlayer (closes #2004)

README.md, RELEASE.md, src/main/config/DEPLOY.md
* #1792
* Document how to perform a release. Reduce time spent on performing a release.
* 
* 
* 
---
> [!NOTE]
=> docs: maven release

pom-dependency-tree.txt, pom.xml, src/main/java/ai/elimu/model/content/multimedia/Audio.java
* #1944
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: remove audio format enum

src/main/config/centos-stream-9/~/.elimu-ai/deploy-webapp.sh
* Resolves #2040 
* Prevents Jetty from being stopped before successfully downloading the WAR file.
* Ensures a more reliable deployment process by handling download failures properly.
* Improves script readability and maintainability.
* The WAR file is now downloaded to a temporary directory (/tmp) instead of the webapps/ directory.
* Jetty is only stopped after confirming that the WAR file has been successfully downloaded.
* Error handling is added to prevent unnecessary Jetty downtime in case of download failure.
* Comments in the script were updated to English for better readability.
* Run the script with a valid version argument:
``` bash
./deploy.sh 1.2.3
```
* Check that the WAR file is downloaded to /tmp first before Jetty is stopped.
* Verify that Jetty stops only after a …
=> Refactor deployment script to prevent unnecessary Jetty downtime

.github/pull_request_template.md, .github/workflows/maven-regression-test-rest.yml, .github/workflows/maven-regression-test-ui.yml
* Resolves #2065
* Run regression tests against the most recent changes in each pull request.
* Sleep 2 minutes before running tests, to give the Jetty server enough time to launch the webapp.
* 
* 
---
> [!NOTE]
=> test: run regression tests against localhost:8080/webapp

src/main/java/ai/elimu/model/content/Emoji.java, src/main/java/ai/elimu/web/content/emoji/EmojiCreateController.java, src/main/java/ai/elimu/web/content/emoji/EmojiEditController.java, src/main/webapp/WEB-INF/jsp/content/emoji/create.jsp, src/main/webapp/WEB-INF/jsp/content/emoji/edit.jsp
* Resolves #2047
* This is needed because we are increasing the minimum Android SDK version.
* Make adjustments in Entity JavaDoc, Controllers, JSPs:
=> chore: change emoji version

pom-dependency-tree.txt, src/main/resources/META-INF/jpa-schema-export.sql
Relates to:
* https://github.com/elimu-ai/webapp/pull/2075
* https://github.com/elimu-ai/webapp/pull/2076
* Resolves #1944
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: schema export

pom-dependency-tree.txt, src/main/java/ai/elimu/entity/content/multimedia/Image.java, src/main/java/ai/elimu/util/GitHubLfsHelper.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/webapp/WEB-INF/jsp/content/multimedia/image/edit.jsp, src/main/webapp/WEB-INF/jsp/content/multimedia/video/edit.jsp
* Resolves #2060
* 
* 
* 
* 
---
> [!NOTE]
=> epub images in lfs

.github/workflows/maven-regression-tests-ENG.yml, .github/workflows/maven-regression-tests-HIN.yml, .github/workflows/maven-regression-tests-TGL.yml, .github/workflows/maven-regression-tests-THA.yml, .github/workflows/maven-regression-tests.yml, pom-dependency-tree.txt, src/main/webapp/WEB-INF/jsp/content/main.jsp, src/main/webapp/WEB-INF/jsp/content/multimedia/image/list.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/list.jsp, src/test/java/selenium/content/MainContentPage.java, src/test/java/selenium/content/image/ImageCreatePage.java, src/test/java/selenium/content/image/ImageEditPage.java, src/test/java/selenium/content/image/ImageListPage.java, src/test/java/selenium/content/image/ImageTest.java, src/test/java/selenium/content/storybook/StoryBookCreatePage.java, src/test/java/selenium/content/storybook/StoryBookEditPage.java, src/test/java/selenium/content/storybook/StoryBookListPage.java, src/test/java/selenium/content/storybook/StoryBookTest.java
* Resolves #2037
* 
* 
* 
* 
---
> [!NOTE]
=> test: improve ui test coverage

pom-dependency-tree.txt, src/main/java/ai/elimu/entity/content/multimedia/Video.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2005108.sql
* Resolves #2137
* 
* 
* 
* 
---
> [!NOTE]
=> feat: store file size of videos

src/main/java/ai/elimu/entity/admin/ApplicationVersion.java, src/main/webapp/WEB-INF/jsp/admin/application-version/create.jsp
* #2153
* 
* 
* 
* 
---
> [!NOTE]
=> add fileurl

pom-dependency-tree.txt, src/main/java/ai/elimu/entity/content/Letter.java, src/main/resources/META-INF/jpa-schema-export.sql, src/main/resources/db/migration/2006007.sql, src/main/webapp/WEB-INF/jsp/content/letter/create.jsp, src/main/webapp/WEB-INF/jsp/content/letter/edit.jsp
closes #2011
* Resolves #1996
* 
* 
* 
* 
---
> [!NOTE]
=> fix: letter text is too long (thai)

pom-dependency-tree.txt, src/main/java/ai/elimu/entity/content/Word.java, src/main/webapp/WEB-INF/jsp/content/word/create.jsp, src/main/webapp/WEB-INF/jsp/content/word/edit.jsp, src/main/webapp/WEB-INF/jsp/content/word/list.jsp
* Resolves #1769
* 
* 
* 
* 
---
> [!NOTE]
=> remove deprecated text property from word

src/main/java/ai/elimu/dao/jpa/GenericDaoJpa.java
* Resolves # 2201
* Modification GenericDaoJpa.java to sort readAll by id
* Modified GenericDaoJpa.java to sort readAll by id
* Modified GenericDaoJpa.java to sort readAll by id
* Modified GenericDaoJpa.java to sort readAll by id
---
> [!NOTE]
=> Modified GenericDaoJpa.java to sort readAll by id

pom-dependency-tree.txt, src/main/java/ai/elimu/web/analytics/students/StudentController.java, src/main/webapp/WEB-INF/jsp/analytics/students/id.jsp
* Resolves #
* 
* 
* 
---
> [!NOTE]
=> feat: display reading speed on analytics dashboard

pom-dependency-tree.txt, pom.xml, src/main/java/ai/elimu/dao/LetterSoundAssessmentEventDao.java, src/main/java/ai/elimu/dao/LetterSoundLearningEventDao.java, src/main/java/ai/elimu/dao/NumberLearningEventDao.java, src/main/java/ai/elimu/dao/StoryBookLearningEventDao.java, src/main/java/ai/elimu/dao/StoryBookParagraphDao.java, src/main/java/ai/elimu/dao/VideoLearningEventDao.java, src/main/java/ai/elimu/dao/WordAssessmentEventDao.java, src/main/java/ai/elimu/dao/WordLearningEventDao.java, src/main/java/ai/elimu/dao/jpa/LetterSoundAssessmentEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/LetterSoundLearningEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/NumberLearningEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/StoryBookLearningEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/StoryBookParagraphDaoJpa.java, src/main/java/ai/elimu/dao/jpa/VideoLearningEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/WordAssessmentEventDaoJpa.java, src/main/java/ai/elimu/dao/jpa/WordLearningEventDaoJpa.java, src/main/java/ai/elimu/web/analytics/MainAnalyticsController.java, src/main/java/ai/elimu/web/analytics/research/experiments/ExperimentController.java, src/main/java/ai/elimu/web/analytics/research/experiments/ExperimentListController.java, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/webapp/WEB-INF/jsp/analytics/main.jsp, src/main/webapp/WEB-INF/jsp/analytics/research/experiments/id.jsp, src/main/webapp/WEB-INF/jsp/analytics/research/experiments/list.jsp, src/test/java/ai/elimu/util/csv/CsvAnalyticsExtractionHelperTest.java
* Resolves #2260
* 
* 
* 
* 
---
> [!NOTE]
=> feat: dashboard for research experiments

pom-dependency-tree.txt, src/main/java/ai/elimu/dao/jpa/StoryBookDaoJpa.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookEditController.java, src/main/webapp/WEB-INF/jsp/content/storybook/create-from-epub.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/create.jsp, src/main/webapp/WEB-INF/jsp/content/storybook/edit.jsp, src/main/webapp/WEB-INF/tags/formErrors.tag
* Resolves #2273
* 
* 
* 
* 
---
> [!NOTE]
=> fix: prevent duplicate epub titles

src/main/java/ai/elimu/util/csv/CsvAnalyticsExtractionHelper.java
Resolves data batch processing error:
```
Error during import of video learning events: class java.lang.IllegalArgumentException: Mapping for learning_event_type not found, expected one of [id, timestamp, package_name, additional_data, research_experiment, experiment_group, video_title, video_id]
```
* Resolves #
* 
* 
* 
* 
---
> [!NOTE]
=> refactor(data): handle removal of the learning event type

pom-dependency-tree.txt, pom.xml
* Resolves #2315
* 
* 
* 
* 
---
> [!NOTE]
=> config: migrate hibernate validator from v7 to v8

pom-dependency-tree.txt, pom.xml, src/main/java/ai/elimu/entity/content/multimedia/Image.java, src/main/java/ai/elimu/rest/v2/JpaToGsonConverter.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCreateController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageCsvExportController.java, src/main/java/ai/elimu/web/content/storybook/StoryBookCreateFromEPubController.java, src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java, src/main/resources/db/migration/2006117.sql, src/main/webapp/WEB-INF/jsp/content/multimedia/image/edit.jsp
* Resolves #2159
* 
* 
* 
* 
---
> [!NOTE]
=> refactor: hex --> rgb

pom-dependency-tree.txt, src/main/java/ai/elimu/web/content/emoji/EmojiEditController.java, src/main/java/ai/elimu/web/content/multimedia/image/ImageEditController.java, src/main/java/ai/elimu/web/content/multimedia/video/VideoEditController.java
#2344
* Resolves #
* 
* 
* 
* 
---
> [!NOTE]
=> fix(ui): disallow content labeling when contributor is not signed on
